# Generated by Django 3.0.6 on 2020-05-11 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image/')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('place', models.CharField(max_length=100)),
                ('pay', models.BooleanField()),
                ('appointment_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('weekDay', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('availability', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Teacher')),
            ],
        ),
    ]
